# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
postgres: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>>

development:
  <<: *default
  database: blog_development
  username: <%= ENV['DATABASE_USER_NAME'] %>
  password: <%= ENV['DATABASE_USER_PASSWORD'] %>

test:
  <<: *default
  database: blog_test
  username: <%= ENV['DATABASE_USER_NAME'] %>
  password: <%= ENV['DATABASE_USER_PASSWORD'] %>

production:
  <<: *default
  database: blog_production
  username: stratos_user
  password: <%= ENV['STRATOS_DATABASE_PASSWORD'] %>